name: continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      MIX_ENV: test

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        elixir: [1.11.2]
        otp: [23.2.4]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

    - name: Install dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: mix deps.get
      
    - name: Check compilation
      run: mix compile --warnings-as-errors

    - name: Run code analysis tools
      run: |
        mix format --check-formatted
        mix credo --strict

    - name: Run tests
      run: |
        mix coveralls.json
        bash <(curl -s https://codecov.io/bash)
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
